# Generated by Django 3.1.2 on 2020-10-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_asset_wishlist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='assets',
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='wishlists',
        ),
    ]
